{
 "title": "Namespace view",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace" }
  ]
 },
 "panels": [
  { "title": "Namespace total statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace total CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "namespace:container_cpu_usage:sum{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace total memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "namespace:container_memory_usage_bytes:sum{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace total CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "namespace:container_cpu_usage:sum{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace total CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "namespace:container_cpu_usage:sum{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "DU CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\", pod=~\".*oai-du.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DU memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_rss{namespace=\"$namespace\",pod=~\".*oai-du.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DU network receive",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"oai\", pod=~\".*oai-du.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DU network transmit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"oai\", pod=~\".*oai-du.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CU-UP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CU-UP CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\", pod=~\".*oai-cu-up.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CU-UP memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_rss{namespace=\"$namespace\",pod=~\".*oai-cu-up.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CU-UP network receive",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"oai\", pod=~\".*oai-cu-up.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CU-UP network transmit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"oai\", pod=~\".*oai-cu-up.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CU-CP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CU-CP CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\", pod=~\".*oai-cu-cp.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CU-CP memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_rss{namespace=\"$namespace\",pod=~\".*oai-cu-cp.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CU-CP network receive",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"oai\", pod=~\".*oai-cu-cp.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CU-CP network transmit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"oai\", pod=~\".*oai-cu-cp.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "NR-UE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "NR-UE CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\", pod=~\".*oai-nr-ue.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NR-UE memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_rss{namespace=\"$namespace\",pod=~\".*oai-nr-ue.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NR-UE network receive",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"oai\", pod=~\".*oai-nr-ue.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NR-UE network transmit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"oai\", pod=~\".*oai-nr-ue.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } }
 ]
}