{{- range .Values.ue }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-configmap-{{ .name }}
data:
  nr-ue.conf: |
      uicc0 = {
      imsi = "{{ .imsi }}";
      key = "{{ $.Values.config.fullKey }}";
      opc = "{{ $.Values.config.opc }}";
      dnn = "{{ $.Values.config.dnn }}";
      nssai_sst = "{{ $.Values.config.sst }}";
      nssai_sd = "{{ $.Values.config.sd }}";
      }
{{- end }}
