{{- range .Values.ue }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-configmap
data:
  nr-ue.conf: |
    uicc0 = {
      imsi = "{{ .imsi }}";           # Use the specific imsi for each UE
      key = "{{ .Values.config.key }}";             # Use the specific key for each UE
      opc = "{{ .Values.config.opc }}";  # Use the shared opc from config
      dnn = "{{ .Values.config.dnn }}";  # Use the shared dnn from config
      nssai_sst = "{{ .Values.config.sst }}";  # Use the shared sst from config
      nssai_sd = "{{ .Values.config.sd }}";    # Use the shared sd from config
    }
{{- end }}
