apiVersion: v1
kind: Service
metadata:
  name: oai-cuup
  labels:
    {{- include "oai-gnb-cu-up.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: n2
      port: 36412
      targetPort: 36412
      protocol: SCTP
    - name: e1
      port: 38462
      targetPort: 38462
      protocol: SCTP
    - name: f1
      port: {{ .Values.config.f1cuPort}}
      targetPort: {{ .Values.config.f1cuPort}}
      protocol: UDP
  selector:
    {{- include "oai-gnb-cu-up.selectorLabels" . | nindent 4 }}
